### ISSUE TITLE
Learning git

### ISSUE THREAD

**Issue by DMSavchik** [DMSavchik/homepage#10]
Let's download the repository using the command line. Git Handbook won't help us much here, so let's just keep Git Reference Manual open in case we get stuck with something and need assistance. Open your favorite terminal, change working directory (cd) to where you'd like to keep the repository (check directory content with ls or dir)
- [x] 1. Execute `git clone` to copy the repository (use https endpoint)
- [x] 2. Check current status with `git status`
- [x] 3. Create new branch with `git branch patch/README.md`, list branches with git branch
- [x] 4. Use `git checkout patch/README.md` to switch branch
- [x] 5. Edit README.md — add "🧙Hocus-pocus!" — and stage it with `git add README.md`
- [x] 6. Commit staged file to Git history with `git commit -m "Abracadabra"` (add a tag with `git tag abracadabra`)
- [x] 7. Try to upload your local changes with `git push --tags` and `git push`. If it fails, it's most likely because there's no such branch on the remote server. Follow Git suggestion and use `--set-upstream origin patch/README.md`
- [x] 8. Look at the current history with `git log`, view detailed information about particular commit with git show (`HEAD`, `HEAD~1`, `HEAD^1`)
- [x] 9. Remove last line from the README.md and see the difference! Using `git diff`, that is. Commit with `git commit -a -m "Undobracadabra"`, add a tag to the latest commit with `git tag undobracadabra`
- [x] 10. Revert the latest commit with `git revert undobracadabra`, add a tag `git tag redobracadabra`
- [x] 11. Now switch to your primary branch (`git checkout develop`) and merge your latest developments into this branch by running `git merge patch/README.md`. Push to the remote with `git push --tags`
- [x] 12. Try to `git fetch`, `git status`, use GitHub online editor to create a new file named **dummy.html** in `develop` branch, and then try to `git fetch` and `git status` again. Finally, use `git pull --rebase`.
- [x] 13. Dismiss everything you did with `git reset --hard abracadabra^`, do `git clean --force` if necessary
- [x] 14. Force-push your local repository to the origin with `git push --force`

**Comment by The-King-of-the-land** [comment]
Good job, peasant.
Looking to see a nice progress from you! 
Don't disappoint your King!

**Comment by DMSavchik** [comment]
@The-King-of-the-land, My Lord this has been completed.
Shell I rest now?
